## Hash Linux
# By BinBash
# .zshrc default file
###################################################################################
# DO NOT EDIT THIS FILE... WRITE YOUR PERSONAL ZSH CONFIG IN ~/.zshrc-personal file
# DO NOT EDIT THIS FILE... WRITE YOUR PERSONAL ZSH CONFIG IN ~/.zshrc-personal file
# DO NOT EDIT THIS FILE... WRITE YOUR PERSONAL ZSH CONFIG IN ~/.zshrc-personal file
###################################################################################



# neofetch
neofetch --ascii_distro archlinux_small

# ZSH Global exntensions
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# Kitty config
autoload -Uz compinit
compinit
# Completion for kitty
kitty + complete setup zsh | source /dev/stdin


# History Configuration
HISTSIZE=5000               #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=5000               #Number of history entries to save to disk
#HISTDUP=erase               #Erase duplicates in the history file
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

[[ ! -f /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme ]] || source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Personal config file 
[[ ! -f ~/.zshrc-personal ]] || source ~/.zshrc-personal


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/hashlinux/.sdkman"
[[ -s "/home/hashlinux/.sdkman/bin/sdkman-init.sh" ]] && source "/home/hashlinux/.sdkman/bin/sdkman-init.sh"
